package Room_related;

public enum MapObjekt {
    STREETNORTH,
    STREETEAST,
    STREETSOUTH,
    STREETWEST,
    HOMESOUTH,
    RECCENTERSOUTH,
    CONCENTERWEST,
    PARKNORTH,
    PLAYGROUNDNORTH,
    PLAYGROUNDEAST,
    PLAYGROUNDWEST,
    NONWALKABLE,
    BEACHEAST
}


